# targets/x86_64/build.conf
CC      = x86_64-elf-gcc
LD      = x86_64-elf-ld
AS      = x86_64-elf-as
NASM    = nasm
ASMFLAGS = -f elf64
CFLAGS  = -ffreestanding -nostdlib -m64 -I src/include -mcmodel=kernel -mno-red-zone -g
LDFLAGS = -T targets/x86_64/linker.ld -n --no-warn-rwx-segments
